### ISSUE TITLE
code review January/15/2020

### ISSUE THREAD

**Issue by SpaYco** [Kyle-Law/Youtube-Clone-Daniel-Kyle#7]
**To Improve**
- you should use fewer arrows on the CSS and more Classes/ID
- Title and the button under the video should be at the same line  

**The Good**
- Responsive Website
- The code is easy to read

**Comment by Kyle-Law** [comment]
Thanks for the review, @Spayco ! I use **arrows** when I want to select similar items under the same parent without naming more classes, **classes** when the items aren't under a same parent, and **id** for a unique item. 

> **To Improve**
> 
> * you should use fewer arrows on the CSS and more Classes/ID
> * Title and the button under the video should be at the same line
>   **The Good**
> * Responsive Website
> * The code is easy to read
